project:
  type: website

website:
  title: "Rochelle Rafn Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
    right:
      - icon: github
        href: https://github.com/rochellerafn
      - icon: linkedin
        href: https://linkedin.com/in/rochellerafn
    

format:
  html:
    theme: lux
    css: styles.css
    toc: true



