project:
  type: website

website:
  title: "Rochelle Rafn Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



